seed: 2026
device: cuda

data:
  track: hml3d263
  sources: [humanml3d]
  mirror_augment: true
  max_motion_len: 196
  min_motion_len: 40

paths:
  eval_matcher: data/official_evaluator/extracted/text_mot_match/model/finest.tar
  eval_stats_dir: data/eval_stats
  hml3d_out_dir: data/HumanML3D_official
  texts_dir: data/HumanML3D_official/texts
  checkpoints_dir: checkpoints
  outputs_dir: outputs

generator:
  max_seq_len: 64
